@file:Suppress("SpellCheckingInspection")
package com.easyml.detection

/**
 * Coordinate space of bounding box coordinates generated by the model.
 */
enum class CoordinateFormat {
    /** Automatically detect normalized [0, 1] vs pixel space based on coordinate magnitudes */
    AUTO,
    /** Coordinates are normalized in range [0, 1] relative to model input dimensions */
    NORMALIZED,
    /** Coordinates are in absolute pixel space [0, modelWidth] and [0, modelHeight] */
    PIXEL_SPACE
}

/**
 * Lightweight candidate detection structure used internally during decoding and NMS.
 *
 * Pre-allocated and reused across frames to prevent heap allocation churn.
 */
data class DetectionCandidate(
    var left: Float = 0f,
    var top: Float = 0f,
    var right: Float = 0f,
    var bottom: Float = 0f,
    var labelIndex: Int = 0,
    var confidence: Float = 0f
) {
    fun set(l: Float, t: Float, r: Float, b: Float, index: Int, conf: Float) {
        this.left = l
        this.top = t
        this.right = r
        this.bottom = b
        this.labelIndex = index
        this.confidence = conf
    }
}

/**
 * Contract for decoding raw model output tensors into candidate detections.
 *
 * Decouples model tensor layouts from the execution engine, enabling deterministic,
 * testable parsing of YOLOv5, YOLOv8, YOLO11, and YOLO26 (both Raw and NMS-free).
 */
interface DetectionDecoder {

    /**
     * Whether this decoder's output is already processed by an End-to-End NMS head.
     * When true, Non-Maximum Suppression is bypassed.
     */
    val isNmsFree: Boolean get() = false

    /**
     * Decode the raw output tensor into candidate detections.
     *
     * @param output The raw output float buffer
     * @param shape The shape of the output tensor (e.g. [1, 84, 8400] or [1, 300, 6])
     * @param modelWidth Model input width in pixels
     * @param modelHeight Model input height in pixels
     * @param confidenceThreshold Minimum confidence score to retain a candidate
     * @param outCandidates Pre-allocated destination list to populate (avoids allocations)
     */
    fun decode(
        output: FloatArray,
        shape: IntArray,
        modelWidth: Int,
        modelHeight: Int,
        confidenceThreshold: Float,
        outCandidates: MutableList<DetectionCandidate>
    )
}

/**
 * Decoder for Ultralytics YOLO26 NMS-Free End-to-End models.
 *
 * Shape: [1, K, 6] or [K, 6] (e.g. [1, 300, 6])
 * Each row contains: [x1, y1, x2, y2, confidence, class_id]
 */
class Yolo26EndToEndDecoder(
    private val coordinateFormat: CoordinateFormat = CoordinateFormat.AUTO
) : DetectionDecoder {

    override val isNmsFree: Boolean get() = true

    override fun decode(
        output: FloatArray,
        shape: IntArray,
        modelWidth: Int,
        modelHeight: Int,
        confidenceThreshold: Float,
        outCandidates: MutableList<DetectionCandidate>
    ) {
        val numDetections = when (shape.size) {
            3 -> shape[1] // [1, K, 6]
            2 -> shape[0] // [K, 6]
            else -> return
        }
        val attributes = when (shape.size) {
            3 -> shape[2]
            2 -> shape[1]
            else -> 6
        }
        if (attributes < 6) return

        var outIndex = 0
        for (i in 0 until numDetections) {
            val base = i * attributes
            val confidence = output[base + 4]
            if (confidence < confidenceThreshold) continue

            var x1 = output[base]
            var y1 = output[base + 1]
            var x2 = output[base + 2]
            var y2 = output[base + 3]
            val classId = output[base + 5].toInt()

            val isNormalized = coordinateFormat == CoordinateFormat.NORMALIZED ||
                (coordinateFormat == CoordinateFormat.AUTO && x1 <= 1.5f && y1 <= 1.5f && x2 <= 1.5f && y2 <= 1.5f)

            if (isNormalized) {
                x1 *= modelWidth
                y1 *= modelHeight
                x2 *= modelWidth
                y2 *= modelHeight
            }

            val left = minOf(x1, x2)
            val top = minOf(y1, y2)
            val right = maxOf(x1, x2)
            val bottom = maxOf(y1, y2)

            if (outIndex < outCandidates.size) {
                outCandidates[outIndex].set(left, top, right, bottom, classId, confidence)
            } else {
                outCandidates.add(DetectionCandidate(left, top, right, bottom, classId, confidence))
            }
            outIndex++
        }
    }
}

/**
 * Decoder for YOLOv8, YOLO11, and YOLO26 Raw (one-to-many) models.
 *
 * Supports both:
 * 1. Transposed format: [1, 4+C, N] where C = classes, N = candidates (default Ultralytics export)
 * 2. Standard format: [1, N, 4+C]
 */
class YoloV8Decoder(
    val isTransposed: Boolean = true,
    private val coordinateFormat: CoordinateFormat = CoordinateFormat.AUTO
) : DetectionDecoder {

    override fun decode(
        output: FloatArray,
        shape: IntArray,
        modelWidth: Int,
        modelHeight: Int,
        confidenceThreshold: Float,
        outCandidates: MutableList<DetectionCandidate>
    ) {
        if (isTransposed) {
            decodeTransposed(output, shape, modelWidth, modelHeight, confidenceThreshold, outCandidates)
        } else {
            decodeStandard(output, shape, modelWidth, modelHeight, confidenceThreshold, outCandidates)
        }
    }

    private fun decodeTransposed(
        output: FloatArray,
        shape: IntArray,
        modelWidth: Int,
        modelHeight: Int,
        confidenceThreshold: Float,
        outCandidates: MutableList<DetectionCandidate>
    ) {
        val numAttributes = shape[1] // 4 + numClasses
        val numDetections = shape[2] // e.g. 8400
        val numClasses = numAttributes - 4
        if (numClasses <= 0 || numDetections <= 0) return

        val row2 = numDetections * 2
        val row3 = numDetections * 3

        var outIndex = 0
        for (i in 0 until numDetections) {
            var maxScore = 0f
            var maxClass = 0

            for (c in 0 until numClasses) {
                val score = output[(4 + c) * numDetections + i]
                if (score > maxScore) {
                    maxScore = score
                    maxClass = c
                }
            }

            if (maxScore < confidenceThreshold) continue

            var cx = output[i]
            var cy = output[numDetections + i]
            var w = output[row2 + i]
            var h = output[row3 + i]

            val isNormalized = coordinateFormat == CoordinateFormat.NORMALIZED ||
                (coordinateFormat == CoordinateFormat.AUTO && cx <= 1.5f && cy <= 1.5f && w <= 1.5f && h <= 1.5f)

            if (isNormalized) {
                cx *= modelWidth
                cy *= modelHeight
                w *= modelWidth
                h *= modelHeight
            }

            val halfW = w * 0.5f
            val halfH = h * 0.5f
            val left = cx - halfW
            val top = cy - halfH
            val right = cx + halfW
            val bottom = cy + halfH

            if (outIndex < outCandidates.size) {
                outCandidates[outIndex].set(left, top, right, bottom, maxClass, maxScore)
            } else {
                outCandidates.add(DetectionCandidate(left, top, right, bottom, maxClass, maxScore))
            }
            outIndex++
        }
    }

    private fun decodeStandard(
        output: FloatArray,
        shape: IntArray,
        modelWidth: Int,
        modelHeight: Int,
        confidenceThreshold: Float,
        outCandidates: MutableList<DetectionCandidate>
    ) {
        val numDetections = if (shape.size == 3) shape[1] else shape[0]
        val numAttributes = if (shape.size == 3) shape[2] else shape[1]
        val numClasses = numAttributes - 4
        if (numClasses <= 0 || numDetections <= 0) return

        var outIndex = 0
        for (i in 0 until numDetections) {
            val base = i * numAttributes

            var maxScore = 0f
            var maxClass = 0
            for (c in 0 until numClasses) {
                val score = output[base + 4 + c]
                if (score > maxScore) {
                    maxScore = score
                    maxClass = c
                }
            }

            if (maxScore < confidenceThreshold) continue

            var cx = output[base]
            var cy = output[base + 1]
            var w = output[base + 2]
            var h = output[base + 3]

            val isNormalized = coordinateFormat == CoordinateFormat.NORMALIZED ||
                (coordinateFormat == CoordinateFormat.AUTO && cx <= 1.5f && cy <= 1.5f && w <= 1.5f && h <= 1.5f)

            if (isNormalized) {
                cx *= modelWidth
                cy *= modelHeight
                w *= modelWidth
                h *= modelHeight
            }

            val halfW = w * 0.5f
            val halfH = h * 0.5f
            val left = cx - halfW
            val top = cy - halfH
            val right = cx + halfW
            val bottom = cy + halfH

            if (outIndex < outCandidates.size) {
                outCandidates[outIndex].set(left, top, right, bottom, maxClass, maxScore)
            } else {
                outCandidates.add(DetectionCandidate(left, top, right, bottom, maxClass, maxScore))
            }
            outIndex++
        }
    }
}

/**
 * Decoder for classic YOLOv5 models.
 *
 * Shape: [1, N, 5+C] where attributes are [cx, cy, w, h, obj_conf, class_scores...]
 * Final confidence is: obj_conf * class_score
 */
class YoloV5Decoder(
    private val hasObjectness: Boolean = true,
    private val coordinateFormat: CoordinateFormat = CoordinateFormat.AUTO
) : DetectionDecoder {

    override fun decode(
        output: FloatArray,
        shape: IntArray,
        modelWidth: Int,
        modelHeight: Int,
        confidenceThreshold: Float,
        outCandidates: MutableList<DetectionCandidate>
    ) {
        val numDetections = if (shape.size == 3) shape[1] else shape[0]
        val numAttributes = if (shape.size == 3) shape[2] else shape[1]
        val classOffset = if (hasObjectness) 5 else 4
        val numClasses = numAttributes - classOffset
        if (numClasses <= 0 || numDetections <= 0) return

        var outIndex = 0
        for (i in 0 until numDetections) {
            val base = i * numAttributes
            val objConf = if (hasObjectness) output[base + 4] else 1f
            if (hasObjectness && objConf < confidenceThreshold * 0.5f) continue

            var maxScore = 0f
            var maxClass = 0
            for (c in 0 until numClasses) {
                val score = output[base + classOffset + c] * objConf
                if (score > maxScore) {
                    maxScore = score
                    maxClass = c
                }
            }

            if (maxScore < confidenceThreshold) continue

            var cx = output[base]
            var cy = output[base + 1]
            var w = output[base + 2]
            var h = output[base + 3]

            val isNormalized = coordinateFormat == CoordinateFormat.NORMALIZED ||
                (coordinateFormat == CoordinateFormat.AUTO && cx <= 1.5f && cy <= 1.5f && w <= 1.5f && h <= 1.5f)

            if (isNormalized) {
                cx *= modelWidth
                cy *= modelHeight
                w *= modelWidth
                h *= modelHeight
            }

            val halfW = w * 0.5f
            val halfH = h * 0.5f
            val left = cx - halfW
            val top = cy - halfH
            val right = cx + halfW
            val bottom = cy + halfH

            if (outIndex < outCandidates.size) {
                outCandidates[outIndex].set(left, top, right, bottom, maxClass, maxScore)
            } else {
                outCandidates.add(DetectionCandidate(left, top, right, bottom, maxClass, maxScore))
            }
            outIndex++
        }
    }
}

/**
 * Universal auto-selecting decoder that detects tensor signature.
 */
class AutoDetectionDecoder : DetectionDecoder {

    private var resolvedDecoder: DetectionDecoder? = null

    override val isNmsFree: Boolean
        get() = resolvedDecoder?.isNmsFree ?: false

    override fun decode(
        output: FloatArray,
        shape: IntArray,
        modelWidth: Int,
        modelHeight: Int,
        confidenceThreshold: Float,
        outCandidates: MutableList<DetectionCandidate>
    ) {
        val decoder = resolvedDecoder ?: resolveDecoder(shape).also { resolvedDecoder = it }
        decoder.decode(output, shape, modelWidth, modelHeight, confidenceThreshold, outCandidates)
    }

    private fun resolveDecoder(shape: IntArray): DetectionDecoder {
        // [1, 300, 6] or [K, 6] -> YOLO26 End-to-End
        if ((shape.size == 3 && shape[2] == 6) || (shape.size == 2 && shape[1] == 6)) {
            return Yolo26EndToEndDecoder()
        }

        // [1, 4+C, N] where C < N -> YOLOv8 / YOLO11 / YOLO26 Raw (transposed)
        if (shape.size == 3 && shape[1] < shape[2]) {
            return YoloV8Decoder(isTransposed = true)
        }

        // [1, N, 85] with 80 classes + 5 -> classic YOLOv5
        if (shape.size == 3 && shape[2] == 85) {
            return YoloV5Decoder(hasObjectness = true)
        }

        // Default fallback to YOLOv8 standard format [1, N, 4+C]
        return YoloV8Decoder(isTransposed = false)
    }
}
